Let's try a completely different approach, without mountpoints.

diff --git a/dev/build-gcc b/dev/build-gcc
--- a/dev/build-gcc
+++ b/dev/build-gcc
@@ -15,55 +15,37 @@ fi
 
 current_dir=$(dirname $(realpath -s "${BASH_SOURCE[0]}"))
 
-rm -rf gcc
 rm -rf built
 
-git clone https://github.com/gcc-mirror/gcc.git --depth=1 $branch gcc || { echo "Couldn't clone GCC."; exit 1; }
-mkdir built
+container_name=build-gcc-$(hostname)-$$
 
-gcc_dir=$(readlink -f ./gcc)
-built_dir=$(readlink -f ./built)
-
-docker run -v $gcc_dir:/gcc -v $built_dir:/built-gcc --rm -e http_proxy=${http_proxy} -e https_proxy=${https_proxy} ubuntu:wily /bin/bash -c '
+docker run --name "${container_name}" -e branch=${branch} -e http_proxy=${http_proxy} -e https_proxy=${https_proxy} ubuntu:wily /bin/bash -c '
 set -x
 
 core_number=$(cat /proc/cpuinfo | grep processor -c)
 make_j=$(($core_number * 3 / 2))
 
 apt-get update
-apt-get install build-essential gcc g++ libgmp-dev libmpfr-dev libmpc-dev gcc-multilib g++-multilib flex bison sudo -y
+apt-get install build-essential gcc g++ libgmp-dev libmpfr-dev libmpc-dev gcc-multilib g++-multilib flex bison -y
 
-TARGET_UID=$(stat -c "%u" /gcc)
-TARGET_GID=$(stat -c "%g" /gcc)
+mkdir /built-gcc
 
-if [[ $UID -ne $TARGET_UID ]]
-then
-    groupadd -g $TARGET_GID builder
-    useradd -u $TARGET_UID -g builder builder
-    command="sudo -u builder bash"
-else
-    command=bash
-fi
-
-$command - << EOF
-
+git clone https://github.com/gcc-mirror/gcc.git --depth=1 $branch gcc || { echo "Couldn't clone GCC."; exit 1; }
 cd gcc
 ./configure --enable-languages=c,c++ --prefix=/usr
 
-make -j$make_j -l$core_number
-make DESTDIR=/built-gcc install
-
-EOF
-'
-exit_status=$?
-
-rm -rf gcc
-
-[[ $exit_status -eq 0 ]] || { echo "Building GCC failed."; exit 1; }
+make -j$make_j -l$core_number && make DESTDIR=/built-gcc install || {
+    docker rm ${container_name}
+    echo "Building GCC failed."
+    exit 1
+}
 
 echo "-- Creating final image."
 
 set -e
+
+docker cp ${container_name}:/built-gcc ./built
+docker rm $(container_name}
 
 pushd built/usr/bin
 ln -sf gcc cc
